# Generated by Django 6.0.1 on 2026-01-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='porcentaje_empleado',
        ),
        migrations.AddField(
            model_name='servicio',
            name='duracion_minutos',
            field=models.PositiveIntegerField(default=60, help_text='Duración estimada del servicio en minutos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicio',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio base del servicio', max_digits=10),
            preserve_default=False,
        ),
    ]
