# Generated by Django 6.0.1 on 2026-01-24 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_remove_servicio_porcentaje_empleado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='porcentaje_empleado',
            field=models.DecimalField(decimal_places=2, default=70, help_text='Porcentaje que recibe el empleado por este servicio', max_digits=5),
            preserve_default=False,
        ),
    ]
