# Generated by Django 6.0.1 on 2026-03-06 21:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicios', '0003_servicio_porcentaje_empleado'),
        ('usuarios', '0002_usuario_telefono_empleado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CajaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('total_servicios', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_empleados', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ganancia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cerrada', models.BooleanField(default=False)),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=100)),
                ('cliente_apellido', models.CharField(max_length=100)),
                ('cliente_telefono', models.CharField(blank=True, max_length=20)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('sena', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='usuarios.empleado')),
            ],
            options={
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ServicioPrestado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.empleado')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='servicios.servicio')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_prestados', to='turnos.turno')),
            ],
        ),
        migrations.CreateModel(
            name='ReporteMensualEmpleado',
            fields=[
            ],
            options={
                'verbose_name': 'Reporte mensual por empleado',
                'verbose_name_plural': 'Reporte mensual por empleado',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('turnos.servicioprestado',),
        ),
    ]
